services:
  api:
    build: .
    container_name: home-services-api-container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /home-services/api
        awslogs-stream: ec2-container
