
services:
  db:
    image: postgres:16
    container_name: home-services-db
    restart: always
    environment:
      POSTGRES_USER: sandy_admin
      POSTGRES_PASSWORD: satyanaidu12
      POSTGRES_DB: home_services_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandy_admin -d home_services_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: home-services-api-container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://sandy_admin:satyanaidu12@db/home_services_db

volumes:
  postgres_data:
